# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'catwalk' do
use_frameworks!

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Firestore'
pod 'Firebase'
pod 'DLRadioButton', '~> 1.4'
end
